### ISSUE TITLE
希望添加轻量级ci工具woodpecker

### ISSUE THREAD

**Issue by xkloveme** [okxlin/appstore#173]
https://woodpecker-ci.org/
![image](https://github.com/okxlin/appstore/assets/29595042/72e544b3-2f94-43db-815e-8d2f9af88217)

**Comment by okxlin** [comment]
收到，有空尝试适配一下。

各种专业工具类应用接触不深，或许只能达到正常跑起来的效果🤪

**Comment by okxlin** [comment]
已更新`Woodpecker CI`，你试试看看有没有什么问题。

**Comment by xkloveme** [comment]
🏃跑失败了，加gitlab CI吧 act runner.  https://gitea.com/gitea/act_runner
```
version: "3"
networks:
    1panel-network:
        external: true
services:
  act_runner:
    image: seepine/act_runner:latest
    networks:
      - 1panel-network
    environment:
      - GITEA_INSTANCE_URL=XXXX
      - GITEA_RUNNER_REGISTRATION_TOKEN=XXXX
      - GITEA_RUNNER_NAME=docker_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - act_data:/data
      - act_cache:/root/.cache
volumes:
  act_data:
  act_cache:
```
