### ISSUE TITLE
请求添加项目九块记账

### ISSUE THREAD

**Issue by chivehao** [okxlin/appstore#2375]
这个MoneyNote(九快记账)我用了一段时间，感觉还不错，电脑端直接使用浏览器，手机端使用chrome访问h5，然后添加到桌面。

官网：https://help.moneynote.com/
github: https://github.com/getmoneynote/moneynote-api
docker部署：https://github.com/getmoneynote/docker-compose-moneynote-ali
文档：https://help.moneynote.com/

我给个我的部署参考，具体配置参考上方docker部署的仓库链接
推荐1panel上的应该是容器分开的，充分利用已经安装的数据库，减少不必要的性能开支

```
version: '3'

services:
  api:
    container_name: moneynote_api
    image: registry.cn-hangzhou.aliyuncs.com/moneynote/moneynote-api:latest
    restart: always
    extra_hosts:
      - "172.21.0.2:192.168.9.10"
    environment:
      - DB_HOST=192.168.9.10
      - DB_PORT=3306
      - DB_NAME=moneynote
      - DB_USER=moneynote
      - DB_PASSWORD=xxxxx
      - invite_code=xxxxx
    ports:
      - "43742:9092"

  pc:
    container_name: moneynote_pc
    links:
      - api
    image: registry.cn-hangzhou.aliyuncs.com/moneynote/moneynote-pc:latest
    restart: always
    environment:
      USER_API_HOST: http://api:9092
    ports:
      - "43743:80"

  h5:
    container_name: moneynote_h5
    links:
      - api
    image: registry.cn-hangzhou.aliyuncs.com/moneynote/moneynote-h5:latest
    restart: always
    environment:
      USER_API_HOST: http://api:9092
    ports:
      - "43744:80"
```
