### ISSUE TITLE
情求添加 loki

### ISSUE THREAD

**Issue by x-haose** [okxlin/appstore#2493]
参考文档：https://grafana.com/docs/loki/latest/setup/install/docker/

loki相关的docker-compose内容：
```yaml
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki


```
