### ISSUE TITLE
【新应用推荐】Hoarder 、Readeck，稍后阅读应用

### ISSUE THREAD

**Issue by tabortao** [okxlin/appstore#2709]
【Hoarder】
项目地址：https://github.com/hoarder-app/hoarder
官网：https://hoarder.app/
简介：一个自托管的书签APP，有AI功能，可永久保存网页。
【Readeck】
项目地址：https://codeberg.org/readeck/readeck
简介：Readeck是一个简单的Web应用程序，可让您保存
您喜欢并希望永久保留的网页的宝贵可读内容。
官网：https://readeck.org/en/
```
version: '3'
services:
    readeck:
        tty: true
        stdin_open: true
        ports:
            - 13801:8000
        volumes:
            - ../readeck/data:/readeck
        image: codeberg.org/readeck/readeck:latest
```
![20241120111149-PixPin](https://github.com/user-attachments/assets/b838779a-3970-484c-8a1e-4a17475ebe62)
![12](https://github.com/user-attachments/assets/ee50c6b0-58f3-4608-94f5-f8bcfe2f3358)
