### ISSUE TITLE
请求增加dufs文件服务器

### ISSUE THREAD

**Issue by tabortao** [okxlin/appstore#2907]
项目地址：https://github.com/sigoden/dufs
docker-compose.yml
```
version: '3.8'

services:
  dufs:
    image: sigoden/dufs:latest          
    container_name: dufs               
    ports:
      - "15032:5000"                     
    volumes:
      - ./data:/data                       
    command: >
      /data       
      -a user:password@/:rw        
      --allow-all
    restart: unless-stopped
```
