### ISSUE TITLE
这个应用可以添加进去【Blossom 云端双链笔记】

### ISSUE THREAD

**Issue by xkloveme** [okxlin/appstore#678]
https://www.wangyunf.com/blossom-doc/

![image](https://github.com/okxlin/appstore/assets/29595042/123c6587-daa3-4392-b06a-5ecf2fc9e0b8)
![image](https://www.wangyunf.com/blossom-doc/imgs/home/home_light.png)

- 有个问题，它内部有 mysql 该如何使用 1panel 的 mysql，而不使用镜像的 mysql

**Comment by xkloveme** [comment]
可以参考下
```
version: "3"

networks:
    1panel-network:
        external: true

services:
    blossom:
        container_name: blossom-backend
        image: jasminexzzz/blossom:latest
        volumes:
            - /opt/1panel/apps/mkdocs-material/mkdocs-material/data/:/home/bl/
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blossom?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8  # 转义连字符
            SPRING_DATASOURCE_USERNAME: blossom
            SPRING_DATASOURCE_PASSWORD: xxxx
            PROJECT_IAAS_BLOS_DEFAULT_PATH: /home/bl/img/  # 修正连接角括号问题
        labels:
            createdBy: xkloveme
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9999/sys/alive"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
        ports:
            - 9999:9999
        networks:
            - 1panel-network
        restart: always
```
